"""RFC-0007 Class C — a disposable Keycloak IdP for testing MFA without prod creds.

Class C means the pipeline OWNS a throwaway identity provider: we provision it,
seed a test user (including its TOTP credential, with a secret WE choose), point
the tests at it, and tear it down. No production credential is ever involved, and
because we set the OTP secret we can generate valid codes (Class B mechanics) for
a real IdP.

Proven 2026-06-17: a realm built here, imported into Keycloak 25, accepted a
`fill_totp` login whose code was generated by the production auth-setup — i.e.
Keycloak's own Java TOTP verifier agreed with our generator.

This module generates the realm + owns the lifecycle. The container backend
(docker/podman) is for local/CI; an in-cluster backend (a k8s Job/Service via
kube_sandbox) is the follow-up for the runtime pod (which has no container
runtime). The realm generation + seed alignment are pure and unit-tested.
"""

from __future__ import annotations

import base64
import json
import secrets
import shutil
import subprocess
import time
import urllib.request
from dataclasses import dataclass


# Keycloak stores an OTP secret as a string and keys the HMAC with its bytes; the
# QR/base32 seed is base32(those bytes). So if WE pick the secret string, the seed
# our generator needs is just its base32 — they key the same HMAC. (Verified
# against the RFC-6238 canonical vector.)
def totp_seed_for(secret: str) -> str:
    """base32 seed (for our login/generator) matching a Keycloak OTP secret."""
    return base64.b32encode(secret.encode()).decode()


def build_realm(
    secret: str,
    *,
    realm: str = "tf-ephemeral",
    username: str = "tester",
    password: str = "test-password",
) -> dict:
    """A Keycloak realm import with a user whose TOTP credential is preset to
    ``secret`` (so codes are generatable). No CONFIGURE_TOTP required action — the
    credential already exists, so the login prompts for OTP and accepts our code.
    """
    return {
        "realm": realm,
        "enabled": True,
        "sslRequired": "none",
        "otpPolicyType": "totp",
        "otpPolicyAlgorithm": "HmacSHA1",
        "otpPolicyDigits": 6,
        "otpPolicyPeriod": 30,
        "users": [
            {
                "username": username,
                "enabled": True,
                "email": f"{username}@example.com",
                "emailVerified": True,
                # Complete the profile so Keycloak does not interrupt the login
                # with an "Update Account Information" required action.
                "firstName": "Test",
                "lastName": "User",
                "requiredActions": [],
                "credentials": [
                    {"type": "password", "value": password, "temporary": False},
                    {
                        "type": "otp",
                        "userLabel": "preset",
                        "secretData": json.dumps({"value": secret}),
                        "credentialData": json.dumps(
                            {
                                "subType": "totp",
                                "digits": 6,
                                "counter": 0,
                                "period": 30,
                                "algorithm": "HmacSHA1",
                            }
                        ),
                    },
                ],
            }
        ],
    }


@dataclass
class EphemeralIdp:
    """A provisioned disposable IdP: where it is + the test identity to use."""

    base_url: str
    realm: str
    username: str
    password: str
    totp_seed: str  # base32 — feed to the fill_totp login (as_totp_secret)

    def account_url(self) -> str:
        return f"{self.base_url}/realms/{self.realm}/account"


def _runtime() -> str:
    for b in ("podman", "docker"):
        if shutil.which(b):
            return b
    raise RuntimeError(
        "no container runtime (need docker or podman) for the local backend"
    )


class EphemeralKeycloak:
    """Context manager: start a throwaway Keycloak with a preset OTP user, then
    ALWAYS tear it down (cost guard: a hard max lifetime). Local/CI backend.

    Usage::

        with EphemeralKeycloak() as idp:
            run_login(idp.account_url(), idp.username, idp.password, idp.totp_seed)
        # container removed here, even on error
    """

    _IMAGE = "quay.io/keycloak/keycloak:25.0"

    def __init__(
        self,
        *,
        port: int = 8480,
        realm: str = "tf-ephemeral",
        username: str = "tester",
        image: str | None = None,
        max_lifetime_s: int = 600,
    ):
        self.port = port
        self.realm = realm
        self.username = username
        self.image = image or self._IMAGE
        self.max_lifetime_s = max_lifetime_s
        self._secret = secrets.token_hex(10)  # printable -> clean base32 seed
        self._name = "tf-kc-" + secrets.token_hex(4)
        self._started = 0.0

    def run_argv(self, binary: str, realm_file: str) -> list[str]:
        """Pure: the container run argv (unit-testable without a runtime)."""
        return [
            binary,
            "run",
            "-d",
            "--rm",
            "--name",
            self._name,
            "-p",
            f"{self.port}:8080",
            "-e",
            "KEYCLOAK_ADMIN=admin",
            "-e",
            "KEYCLOAK_ADMIN_PASSWORD=admin",
            "-v",
            f"{realm_file}:/opt/keycloak/data/import/realm.json:ro",
            self.image,
            "start-dev",
            "--import-realm",
        ]

    def __enter__(self) -> EphemeralIdp:
        import tempfile
        from pathlib import Path

        rt = _runtime()
        tmp = Path(tempfile.mkdtemp(prefix="tf-kc-"))
        realm_file = tmp / "realm.json"
        # The realm JSON necessarily carries the OTP seed for the throwaway test
        # user: Keycloak's --import-realm reads it from disk at boot, so it
        # cannot be passed by reference. This is a per-run ephemeral secret
        # (secrets.token_hex, generated in __init__) for a disposable IdP that
        # is always torn down (cost-guard max_lifetime_s) — never a real or
        # long-lived credential. Written 0600 inside a 0700 mkdtemp dir.
        # (CWE-312: ephemeral-by-design test credential.)
        realm_file.write_text(
            json.dumps(
                build_realm(self._secret, realm=self.realm, username=self.username)
            )
        )
        realm_file.chmod(0o600)
        argv = self.run_argv(rt, str(realm_file))
        subprocess.run(argv, check=True, capture_output=True, text=True, timeout=120)
        self._started = time.monotonic()
        self._await_ready()
        base = f"http://127.0.0.1:{self.port}"
        return EphemeralIdp(
            base_url=base,
            realm=self.realm,
            username=self.username,
            password="test-password",
            totp_seed=totp_seed_for(self._secret),
        )

    def _await_ready(self, timeout_s: int = 90) -> None:
        url = f"http://127.0.0.1:{self.port}/realms/{self.realm}/.well-known/openid-configuration"
        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            try:
                with urllib.request.urlopen(url, timeout=3) as r:
                    if r.status == 200:
                        return
            except Exception:  # noqa: BLE001 - keep polling until the deadline
                time.sleep(2)
        raise RuntimeError(f"ephemeral Keycloak not ready within {timeout_s}s")

    def __exit__(self, *exc) -> None:
        # Cost guard + mandatory teardown: remove the container no matter what.
        try:
            subprocess.run(
                [_runtime(), "rm", "-f", self._name],
                check=False,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except Exception:  # noqa: BLE001 - teardown is best-effort, never raises
            pass
