"""Render a CorrectionRequest as a QA_FIX_REQUEST.md payload (#184).

Part of epic #182. AIFactory's QA Fixer (`qa/fixer.py::run_qa_fixer_session`)
reads a free-form ``QA_FIX_REQUEST.md`` from the spec dir, so the exact layout
is ours to define — the only contract is "readable markdown describing what to
fix". This renderer is **deterministic** (no time, no randomness): failures are
pre-sorted by ``build_correction_request`` so the same input always yields the
same markdown, which makes it snapshot-testable and produces clean diffs.
"""

from __future__ import annotations

from .request import CorrectionRequest

__all__ = ["render_fix_request_md"]


def render_fix_request_md(request: CorrectionRequest) -> str:
    """Render the ``QA_FIX_REQUEST.md`` body for AIFactory's QA Fixer."""
    task_id = request.aifactory_task_id
    lines: list[str] = [
        "# QA Fix Request — from TFactory",
        "",
        f"> Hand-back from TFactory (epic #182) for AIFactory spec `{task_id}`.",
        "> TFactory's tests surfaced problems in this feature. Fix the code under",
        "> test so the items below pass — do not weaken or delete the tests.",
        "",
        "## Summary",
        "",
        f"- **Spec:** `{task_id}`",
        f"- **Failing tests:** {len(request.failures)}",
        f"- **Source:** {request.source_kind}",
        "",
    ]

    if request.failures:
        lines += ["## Failures", ""]
        for i, f in enumerate(request.failures, start=1):
            loc = f"`{f.test_file}`" if f.test_file else "(file unknown)"
            lane = f", lane: {f.lane}" if f.lane else ""
            lines += [
                f"### {i}. {f.test_id}  ({loc}{lane})",
                "",
                f"- **Verdict:** {f.verdict}",
                f"- **Acceptance criterion:** {f.acceptance_criterion or '—'}",
                f"- **Observed:** {f.reason}",
                "",
            ]

    if request.visual_plan:
        lines += [
            "## Visual inspection findings",
            "",
            request.visual_plan.strip(),
            "",
        ]

    lines += [
        "---",
        "_Auto-generated by TFactory hand-back. Apply fixes, then re-run TFactory "
        "to verify._",
        "",
    ]
    return "\n".join(lines)
