"""Render a CorrectionRequest as a QA_FIX_REQUEST.md payload (#184).

Part of epic #182. AIFactory's QA Fixer (`qa/fixer.py::run_qa_fixer_session`)
reads a free-form ``QA_FIX_REQUEST.md`` from the spec dir, so the exact layout
is ours to define — the only contract is "readable markdown describing what to
fix". This renderer is **deterministic** (no time, no randomness): failures are
pre-sorted by ``build_correction_request`` so the same input always yields the
same markdown, which makes it snapshot-testable and produces clean diffs.
"""

from __future__ import annotations

from .request import CorrectionRequest, Failure

__all__ = ["render_fix_request_md"]

_MODEL_LABEL = "Evaluator model's rationale (LLM-authored, not verified)"
_NO_REASON = "(no reason recorded)"


def _reason_md(f: Failure) -> list[str]:
    """Measured lines and the model's rationale, labelled apart (#1195).

    This used to be one ``Observed:`` line, which presented the judge LLM's
    interpretation with the authority of a measurement — and the QA Fixer acts
    on it as instructions.
    """
    system = "; ".join(t for t, s in f.reasons if s == "system")
    model = "; ".join(t for t, s in f.reasons if s == "model")
    if not f.reasons and f.reason != _NO_REASON:
        # No reasons list: ``reason`` is the judge's own fallback field
        # (``reason`` / ``semantic_relevance``), so it is model text too.
        model = f.reason
    out = [f"- **Measured:** {system}"] if system else []
    if model:
        out.append(f"- **{_MODEL_LABEL}:** {model}")
    return out or [f"- **Reason:** {_NO_REASON}"]


def render_fix_request_md(request: CorrectionRequest) -> str:
    """Render the ``QA_FIX_REQUEST.md`` body for AIFactory's QA Fixer."""
    task_id = request.aifactory_task_id
    lines: list[str] = [
        "# QA Fix Request — from TFactory",
        "",
        f"> Hand-back from TFactory (epic #182) for AIFactory spec `{task_id}`.",
        "> TFactory's tests surfaced problems in this feature. Fix the code under",
        "> test so the items below pass — do not weaken or delete the tests.",
        "> Lines marked LLM-authored are the Evaluator model's interpretation,",
        "> not a measurement — verify them before acting on them.",
        "",
        "## Summary",
        "",
        f"- **Spec:** `{task_id}`",
        f"- **Failing tests:** {len(request.failures)}",
        f"- **Source:** {request.source_kind}",
        "",
    ]

    if request.failures:
        lines += ["## Failures", ""]
        for i, f in enumerate(request.failures, start=1):
            loc = f"`{f.test_file}`" if f.test_file else "(file unknown)"
            lane = f", lane: {f.lane}" if f.lane else ""
            lines += [
                f"### {i}. {f.test_id}  ({loc}{lane})",
                "",
                f"- **Verdict:** {f.verdict}",
                f"- **Acceptance criterion:** {f.acceptance_criterion or '—'}",
                *_reason_md(f),
                "",
            ]

    if request.visual_plan:
        lines += [
            "## Visual inspection findings",
            "",
            request.visual_plan.strip(),
            "",
        ]

    lines += [
        "---",
        "_Auto-generated by TFactory hand-back. Apply fixes, then re-run TFactory "
        "to verify._",
        "",
    ]
    return "\n".join(lines)
